# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlE8K2PFR07gackap48wHqEJ3u66OG6i
"""

# SIMULACIÓN DE VPN SENCILLA EN PYTHON
# No usa certificados, no usa terminal extra, todo es una DEMO educativa.
# Muestra cómo: Cliente → Cifra → Túnel → Servidor → Descifra

import time

# ------------------------------------------
# 1. Funciones de cifrado y descifrado
# ------------------------------------------
# Usamos un cifrado XOR muy simple para demostrar la idea.
# En una VPN REAL se usa AES, RSA, Diffie-Hellman, etc.

def cifrar(texto, clave):
    return "".join(chr(ord(c) ^ clave) for c in texto)

def descifrar(texto_cifrado, clave):
    return "".join(chr(ord(c) ^ clave) for c in texto_cifrado)

# ------------------------------------------
# 2. Cliente (simulado)
# ------------------------------------------

def cliente_envia(mensaje):
    print("\n--- CLIENTE ---")
    print("Mensaje original:", mensaje)

    clave = 27  # clave de cifrado (demo)
    mensaje_cifrado = cifrar(mensaje, clave)

    print("Mensaje CIFRADO que viaja por el túnel:", mensaje_cifrado)

    # Simula que se envía al servidor
    time.sleep(1)

    respuesta_cifrada = servidor_recibe(mensaje_cifrado, clave)
    respuesta_descifrada = descifrar(respuesta_cifrada, clave)

    print("Respuesta descifrada del servidor:", respuesta_descifrada)

# ------------------------------------------
# 3. Servidor (simulado)
# ------------------------------------------

def servidor_recibe(mensaje_cifrado, clave):
    print("\n--- SERVIDOR ---")
    print("Mensaje cifrado recibido:", mensaje_cifrado)

    mensaje_descifrado = descifrar(mensaje_cifrado, clave)
    print("Mensaje DESCIFRADO:", mensaje_descifrado)

    # Servidor procesa y responde
    respuesta = f"Servidor recibió tu mensaje: '{mensaje_descifrado}'"
    respuesta_cifrada = cifrar(respuesta, clave)

    print("Respuesta cifrada enviada al cliente:", respuesta_cifrada)

    return respuesta_cifrada

# ------------------------------------------
# 4. Ejecutar la simulación
# ------------------------------------------

cliente_envia("Hola, esto es una simulación de VPN.")